# AirSim multirotor monocular Camera
#==============#
# Camera Model #
#==============#
Camera:
  name: "AirSim Copter Camera"
  setup: "monocular"
  model: "perspective"
  fx: 640.0
  fy: 640.0
  cx: 640.0
  cy: 360.0
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  fps: 30.0
  cols: 1280
  rows: 720
  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#
Preprocessing:
  min_size: 1280

#================#
# ORB Parameters #
#================#
Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#
Mapping:
  backend: "g2o"
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20
  erase_temporal_keyframes: false
  num_temporal_keyframes: 15

Tracking:
  backend: "g2o"
  enable_temporal_keyframe_only_tracking: false

KeyframeInserter:
  wait_for_local_bundle_adjustment: false

Relocalizer:
  search_neighbor: true

LoopDetector:
  backend: "g2o"

#===========================#
# PangolinViewer Parameters #
#===========================#
PangolinViewer:
  keyframe_size: 0.015
  landmark_size: 0.1
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400
