# raspi/lib_rpi/webcam_config.yaml

# --- Camera Parameters ---
Camera:
  name: "MyWebcam"
  setup: "monocular"
  model: "perspective"

  # GANTI ANGKA INI DENGAN HASIL KALIBRASI ANDA
  # Ini adalah contoh generik 640x480 (FOV ~60 derajat)
  fx: 702.74467
  fy: 668.46267
  cx: 313.36048
  cy: 204.10211

  # Distorsi (k1, k2, p1, p2, k3) - Set 0 jika tidak yakin/belum kalibrasi
  k1: -0.54212
  k2: 0.35908
  p1: 0.04498
  p2: 0.00725
  k3: -0.55308

  # Frame rate kamera Anda (biasanya 30)
  fps: 30.0

  # Resolusi (Harus sama persis dengan yang diset di script run)
  cols: 640
  rows: 480

  # Color order: RGB or BGR (OpenCV uses BGR usually)
  color_order: "BGR"

# --- Feature Extraction (ORB) ---
Feature:
  max_num_keypoints: 500 # Kurangi ke 1000 untuk RPi agar ringan
  scale_factor: 1.2
  num_levels: 4
  ini_fast_threshold: 20
  min_fast_threshold: 7

# --- Socket Viewer ---
SocketPublisher:
  # Ganti IP ini nanti via script atau manual
  server_uri: "http://192.168.11.137:3000"
